language: ruby

matrix:
  include:
    - rvm: 2.4.6
      gemfile: Gemfile
    - rvm: 2.5.5
      gemfile: Gemfile
    - rvm: 2.6.3
      gemfile: gemfiles/Gemfile.ilm
    - rvm: 2.6.3
      gemfile: gemfiles/Gemfile.elasticsearch.v6
    - rvm: 2.6.3
      gemfile: Gemfile
    - rvm: 2.7.0
      gemfile: Gemfile

gemfile:
 - Gemfile

before_install:
  - gem update --system=2.7.8

script: bundle exec rake test
sudo: false
