language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2

script:
  - bundle exec ruby -S -Itest test/plugin/test_out_elasticsearch.rb
  - bundle exec ruby -S -Itest test/plugin/test_out_elasticsearch_dynamic.rb
